// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Predicts the Air Quality Index (AQI) for a given city based on historical data.
 *
 * - predictAqi - A function that handles the AQI prediction process.
 * - PredictAqiInput - The input type for the predictAqi function.
 * - PredictAqiOutput - The return type for the predictAqi function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';
import {City} from '@/services/air-quality';

const PredictAqiInputSchema = z.object({
  city: z.object({
    name: z.string().describe('The name of the city.'),
    latitude: z.number().describe('The latitude of the city.'),
    longitude: z.number().describe('The longitude of the city.'),
  }).describe('The city for which to predict AQI.'),
  historicalAqiData: z.array(
    z.object({
      aqi: z.number().describe('The AQI value for a specific day.'),
    })
  ).describe('Historical AQI data for the past 7 days.'),
});

export type PredictAqiInput = z.infer<typeof PredictAqiInputSchema>;

const PredictAqiOutputSchema = z.object({
  predictedAqi: z.number().describe('The predicted AQI value for the next day.'),
});

export type PredictAqiOutput = z.infer<typeof PredictAqiOutputSchema>;

export async function predictAqi(input: PredictAqiInput): Promise<PredictAqiOutput> {
  return predictAqiFlow(input);
}

const prompt = ai.definePrompt({
  name: 'predictAqiPrompt',
  input: {
    schema: z.object({
      city: z.object({
        name: z.string().describe('The name of the city.'),
        latitude: z.number().describe('The latitude of the city.'),
        longitude: z.number().describe('The longitude of the city.'),
      }).describe('The city for which to predict AQI.'),
      historicalAqiData: z.array(
        z.object({
          aqi: z.number().describe('The AQI value for a specific day.'),
        })
      ).describe('Historical AQI data for the past 7 days.'),
    }),
  },
  output: {
    schema: z.object({
      predictedAqi: z.number().describe('The predicted AQI value for the next day.'),
    }),
  },
  prompt: `You are an AI assistant specializing in predicting Air Quality Index (AQI) for cities in India.

  You are given historical AQI data and will use a simple linear regression model to predict the AQI for the next day.

  City: {{city.name}}

  Historical AQI Data:
  {{#each historicalAqiData}}
  - AQI: {{this.aqi}}
  {{/each}}

  Based on the provided data, predict the AQI for the next day.
  Let me know the predicted AQI value only, without any intro or outro text. No explanation is needed.
  `,
});

const predictAqiFlow = ai.defineFlow<
  typeof PredictAqiInputSchema,
  typeof PredictAqiOutputSchema
>({
  name: 'predictAqiFlow',
  inputSchema: PredictAqiInputSchema,
  outputSchema: PredictAqiOutputSchema,
}, async input => {
  const {output} = await prompt(input);
  return output!;
});
